### ISSUE TITLE
Could not determine platform on Jetson Nano

### ISSUE THREAD

**Issue by kaibaooo** [adafruit/Adafruit_Python_GPIO#109]
**Board:** NVIDIA Jetson Nano
**OS:** Linux 4.9.140-tegra #1 SMP PREEMPT Wed Mar 13 00:32:22 PDT 2019 aarch64 aarch64 aarch64 GNU/Linux Ubuntu 18.04
**Python Version** : Python 3.6.8
**Error Messages :** 
```
nuk-jetson-nano@nukjetsonnano-desktop:~$ python3 oled.py 
Traceback (most recent call last):
  File "oled.py", line 18, in <module>
    disp = Adafruit_SSD1306.SSD1306_128_64(rst=0)
  File "/home/nuk-jetson-nano/.local/lib/python3.6/site-packages/Adafruit_SSD1306/SSD1306.py", line 243, in __init__
    gpio, spi, i2c_bus, i2c_address, i2c)
  File "/home/nuk-jetson-nano/.local/lib/python3.6/site-packages/Adafruit_SSD1306/SSD1306.py", line 85, in __init__
    self._gpio = GPIO.get_platform_gpio()
  File "/home/nuk-jetson-nano/.local/lib/python3.6/site-packages/Adafruit_GPIO/GPIO.py", line 426, in get_platform_gpio
    raise RuntimeError('Could not determine platform.')
RuntimeError: Could not determine platform.
```
**Description:** I try Adafruit_SSD1306 on Jetson Nano but it cannot work for the Adafruit_GPIO exception.

**Comment by ladyada** [comment]
please try the new circuitpython/blinka codebase

https://learn.adafruit.com/adafruit-pioled-128x32-mini-oled-for-raspberry-pi/usage
