### ISSUE TITLE
Adafruit_Python_CharLCD - fails if left running

### ISSUE THREAD

**Issue by harvybob** [adafruit/Adafruit_Python_GPIO#39]
Using the demo char_lcd_plate.py from Adafruit_Python_CharLCD, if you leave the script running waiting for input i eventually get the following error:
`:~/Adafruit_Python_CharLCD/examples $ Press Ctrl-C to quit.
Traceback (most recent call last):
  File "char_lcd_plate.py", line 71, in <module>
    if lcd.is_pressed(button[0]):
  File "build/bdist.linux-armv6l/egg/Adafruit_CharLCD/Adafruit_CharLCD.py", line 450, in is_pressed
  File "build/bdist.linux-armv6l/egg/Adafruit_GPIO/MCP230xx.py", line 95, in input
  File "build/bdist.linux-armv6l/egg/Adafruit_GPIO/MCP230xx.py", line 103, in input_pins
  File "build/bdist.linux-armv6l/egg/Adafruit_GPIO/I2C.py", line 129, in readList
IOError: [Errno 5] Input/output error`

using raspiaban - both wheezy and jessie on raspberry pi B

**Comment by harvybob** [comment]
Think this may be a connection issue.

I removed the board from a breadboard and connected directly, so far (60 odd hours later) it is still running

Please close.
