### ISSUE TITLE
Support arm64 for platform version

### ISSUE THREAD

**Issue by vincentrou** [adafruit/Adafruit_Python_GPIO#84]
On linux arm64 there is no hardware info in `/proc/cpuinfo`, it needs to get platform from `/proc/device-tree/model`

```
$ sudo python3 examples/simpletest.py 
Traceback (most recent call last):
  File "examples/simpletest.py", line 12, in <module>
    adc = Adafruit_ADS1x15.ADS1115()
  File "/usr/local/lib/python3.5/dist-packages/Adafruit_ADS1x15-1.0.2-py3.5.egg/Adafruit_ADS1x15/ADS1x15.py", line 319, in __init__
  File "/usr/local/lib/python3.5/dist-packages/Adafruit_ADS1x15-1.0.2-py3.5.egg/Adafruit_ADS1x15/ADS1x15.py", line 82, in __init__
  File "/usr/local/lib/python3.5/dist-packages/Adafruit_GPIO-1.0.3-py3.5.egg/Adafruit_GPIO/I2C.py", line 65, in get_i2c_device
  File "/usr/local/lib/python3.5/dist-packages/Adafruit_GPIO-1.0.3-py3.5.egg/Adafruit_GPIO/I2C.py", line 57, in get_default_bus
RuntimeError: Could not determine default I2C bus for platform.
```

Initial issues :
https://github.com/bamarni/pi64/issues/35
https://github.com/raspberrypi/linux/issues/2110

**Comment by ladyada** [comment]
hiya thank you for the issue. we're going to be deprecating this library in favor of [our python3 Blinka library](https://github.com/adafruit/Adafruit_Blinka) which has [support for almost 200 different drivers](https://circuitpython.readthedocs.io/projects/bundle/en/latest/drivers.html), and a [wide variety of linux computers](https://circuitpython.org/blinka) as well as [ft232h
](https://learn.adafruit.com/circuitpython-on-any-computer-with-ft232h)
If this issue is still occuring when you use Blinka, please re-open it there!
